version: '3.8'
services:
  vprodb:
    build:
      context: ./Docker-files/db
    image: kabbo06/vprodb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass 
    
  vprocache01:
    image: memcached
    ports:
      - "11211:11211"
  
  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    
  vproapp:
    build:
      context: ./Docker-files/app
    image: kabbo06/vproapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/var/local/webapps

  vproweb:
    build:
      context: ./Docker-files/web
    image: kabbo06/vproweb
    container_name: vproweb
    ports:
      - "80:80"
    
volumes:
  vprodbdata: {}
  vproappdata: {}
